# Pelabelan Data Menggunakan Lexicon

In [1]:
import pandas as pd
import re
import string
import numpy as np
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import word_tokenize

In [2]:
df = pd.read_csv("datasetReady.csv")
df

                                                tweets  label
0         ['tanjung', 'balai', 'laksana', 'vaksinasi']    1.0
1    ['dukung', 'program', 'juta', 'vaksinasi', 'lu...    1.0
2              ['sebut', 'lonjak', 'covid', 'kendali']    1.0
3    ['lampung', 'gelar', 'vaksinasi', 'covid', 'an...    1.0
4    ['bupati', 'kobar', 'apresiasi', 'usaha', 'lak...    1.0
..                                                 ...    ...
787  ['grab', 'luncur', 'pusat', 'vaksinasi', 'rama...    1.0
788  ['cegah', 'sebar', 'covid', 'sentra', 'vaksina...    1.0
789  ['neng', 'liat', 'animo', 'teman', 'teman', 'v...    1.0
790  ['lonjak', 'covid', 'izin', 'vaksin', 'vaksina...    0.0
791  ['bahas', 'militer', 'bantu', 'vaksinasi', 'te...    1.0

[792 rows x 2 columns]

In [3]:
word_dict = {}
for i in range(0,len(df['tweets'])):
    sentence = df['tweets'][i]
    word_token = word_tokenize(sentence)
    for j in word_token:
        if j not in word_dict:
            word_dict[j] = 1
        else:
            word_dict[j] += 1

In [4]:
len(word_dict)

2234

In [5]:
len({k:v for (k,v) in word_dict.items() if v < 4})

1803

In [6]:
negasi = ['bukan','tidak','ga','gk']
lexicon = pd.read_csv('lexicon/modified_full_lexicon.csv')
lexicon = lexicon.drop(lexicon[(lexicon['word'] == 'bukan')
                               |(lexicon['word'] == 'tidak')
                               |(lexicon['word'] == 'ga')|(lexicon['word'] == 'gk') ].index,axis=0)
lexicon = lexicon.reset_index(drop=True)

In [7]:
len(lexicon)

10248

In [8]:
lexicon.head(10)

        word  weight  number_of_words
0        hai       3                1
1    merekam       2                1
2  ekstensif       3                1
3  paripurna       1                1
4     detail       2                1
5     pernik       3                1
6      belas       2                1
7      welas       4                1
8     kabung       1                1
9     rahayu       4                1

In [9]:
lexicon_word = lexicon['word'].to_list()
lexicon_num_words = lexicon['number_of_words']

In [10]:
len(lexicon_word)

10248

In [ ]:
ns_words = []
factory = StemmerFactory()
stemmer = factory.create_stemmer()
for word in word_dict.keys():
    if word not in lexicon_word:
        kata_dasar = stemmer.stem(word)
        if kata_dasar not in lexicon_word:
            ns_words.append(word)
len(ns_words)

In [34]:
len({k:v for (k,v) in word_dict.items() if ((k in ns_words)&(v>3)) })

261

In [35]:
ns_words_list = {k:v for (k,v) in word_dict.items() if ((k in ns_words)&(v>3))}

In [36]:
sort_orders = sorted(ns_words_list.items(), key=lambda x: x[1], reverse=True)
sort_orders=sort_orders[0:20]
for i in sort_orders:
    print(i[0], i[1])

admin 323
byu 228
kak 217
pakai 163
mbps 126
dm 119
gb 111
tidak 71
yaa 71
kakak 67
unlimited 59
sinyal 57
bagaimana 56
ribu 55
by 49
kartu 47
jam 42
bisa 40
nindy 36
no 34

In [37]:
lexicon['number_of_words'].value_counts()

1    9536
2     686
3      24
4       2
Name: number_of_words, dtype: int64

In [39]:
sencol =[]
senrow =np.array([])
nsen = 0
factory = StemmerFactory()
stemmer = factory.create_stemmer()
sentiment_list = []
# function to write the word's sentiment if it is founded
def found_word(ind,words,word,sen,sencol,sentiment,add):
    # if it is already included in the bag of words matrix, then just increase the value
    if word in sencol:
        sen[sencol.index(word)] += 1
    else:
    #if not, than add new word
        sencol.append(word)
        sen.append(1)
        add += 1
    #if there is a negation word before it, the sentiment would be the negation of it's sentiment
    if (words[ind-1] in negasi):
        sentiment += -lexicon['weight'][lexicon_word.index(word)]
    else:
        sentiment += lexicon['weight'][lexicon_word.index(word)]
    
    return sen,sencol,sentiment,add
            
# checking every words, if they are appear in the lexicon, and then calculate their sentiment if they do
for i in range(len(df)):
    nsen = senrow.shape[0]
    words = word_tokenize(df['tweets'][i])
    sentiment = 0 
    add = 0
    prev = [0 for ii in range(len(words))]
    n_words = len(words)
    if len(sencol)>0:
        sen =[0 for j in range(len(sencol))]
    else:
        sen =[]
    
    for word in words:
        ind = words.index(word)
        # check whether they are included in the lexicon
        if word in lexicon_word :
            sen,sencol,sentiment,add= found_word(ind,words,word,sen,sencol,sentiment,add)
        else:
        # if not, then check the root word
            kata_dasar = stemmer.stem(word)
            if kata_dasar in lexicon_word:
                sen,sencol,sentiment,add= found_word(ind,words,kata_dasar,sen,sencol,sentiment,add)
        # if still negative, try to match the combination of words with the adjacent words
            elif(n_words>1):
                if ind-1>-1:
                    back_1    = words[ind-1]+' '+word
                    if (back_1 in lexicon_word):
                        sen,sencol,sentiment,add= found_word(ind,words,back_1,sen,sencol,sentiment,add)
                    elif(ind-2>-1):
                        back_2    = words[ind-2]+' '+back_1
                        if back_2 in lexicon_word:
                            sen,sencol,sentiment,add= found_word(ind,words,back_2,sen,sencol,sentiment,add)
    # if there is new word founded, then expand the matrix
    if add>0:  
        if i>0:
            if (nsen==0):
                senrow = np.zeros([i,add],dtype=int)
            elif(i!=nsen):
                padding_h = np.zeros([nsen,add],dtype=int)
                senrow = np.hstack((senrow,padding_h))
                padding_v = np.zeros([(i-nsen),senrow.shape[1]],dtype=int)
                senrow = np.vstack((senrow,padding_v))
            else:
                padding =np.zeros([nsen,add],dtype=int)
                senrow = np.hstack((senrow,padding))
            senrow = np.vstack((senrow,sen))
        if i==0:
            senrow = np.array(sen).reshape(1,len(sen))
    # if there isn't then just update the old matrix
    elif(nsen>0):
        senrow = np.vstack((senrow,sen))
        
    sentiment_list.append(sentiment)

In [40]:
len(sentiment_list)

1729

In [41]:
print(senrow.shape[0])

1729

In [42]:
sencol.append('sentiment')
sentiment_array = np.array(sentiment_list).reshape(senrow.shape[0],1)
sentiment_data = np.hstack((senrow,sentiment_array))
df_sen = pd.DataFrame(sentiment_data,columns = sencol)

In [43]:
df_sen.head(10)

,aplikasi,buka,akses,cek,kuota,beli,pengertian,banget,makasih,bantuin,...,closed,bawel,sampean,cuek,duh,curang,dalem,saksi,bangga,sentiment
0,1,1,1,1,2,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-5
1,0,0,0,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,8
2,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,11
4,0,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,4
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
7,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,8
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2

In [50]:
cek_df = pd.DataFrame([])
cek_df['text'] = df['teks'].copy()
cek_df['sentiment']  = df_sen['sentiment'].copy()

In [51]:
cek_df.head(10)

                                                text  sentiment
0  Ini gimana kok berhariÂ² aplikasi gak bisa dibu...         -5
1  Min @byu_id ini pengertian beud, makasih ya......          8
2  @byu_id hei masa tiap bulan begini terus.. ban...          5
3  Ya Allah jaringan @byu_id jelek bgt udah hubun...         11
4  @amourtabells @byu_id Paket unlimited Xl 1 bul...          4
5  Alhamdulillah... Terima kasih @byu_id https://...          9
6  @byu_id Min tetep di 2 Mbps aja ya, jangan bal...          2
7  Kirain ini prank, ternyata beneran bisa tingga...          8
8  Ini beneran ga min??\n@byu_id https://t.co/3NV...          3
9  @esmrld___ @txtdrhotel @byu_id Sama bgt,halo k...          2

In [52]:
cek_df['sentiment']  = df_sen['sentiment'].copy()
df.loc[cek_df['sentiment']>0, 'sentiment'] = 1 #positive
df.loc[cek_df['sentiment']<0, 'sentiment'] = 0 #negative
df.loc[cek_df['sentiment']==0, 'sentiment'] = 2 #netral
df.drop(df[cek_df.sentiment==0].index, inplace=True)
df.reset_index()

,index,Unnamed: 0,Unnamed: 0.1,waktu,id,username,teks,cleansing,case_folding,tokenize,stopwords,normalisasi,sentiment
0,0,0,0,2021-06-30 23:01:28,1410372945520652291,Dito (ãƒ‡ã‚£ãƒˆ),Ini gimana kok berhariÂ² aplikasi gak bisa dibu...,Ini gimana kok berhari aplikasi gak bisa dibuk...,ini gimana kok berhari aplikasi gak bisa dibuk...,"['ini', 'gimana', 'kok', 'berhari', 'aplikasi'...","['gimana', 'berhari', 'aplikasi', 'dibuka', 'w...",bagaimana berhari aplikasi dibuka website diak...,0.0
1,1,1,1,2021-06-30 23:00:27,1410372691446558721,Magnet Kulkas,"Min @byu_id ini pengertian beud, makasih ya......",Min ini pengertian beud makasih ya Cus nonton ...,min ini pengertian beud makasih ya cus nonton ...,"['min', 'ini', 'pengertian', 'beud', 'makasih'...","['min', 'pengertian', 'beud', 'makasih', 'cus'...",admin pengertian banget makasih cus nonton,1.0
2,2,2,2,2021-06-30 23:00:10,1410372619170324481,Anfhd,@byu_id hei masa tiap bulan begini terus.. ban...,hei masa tiap bulan begini terus bantuin sini ...,hei masa tiap bulan begini terus bantuin sini ...,"['hei', 'masa', 'tiap', 'bulan', 'begini', 'te...","['hei', 'bantuin', 'kirim', 'dm']",hei bantuin kirim dm,1.0
3,3,3,3,2021-06-30 22:10:27,1410360109385936898,Fructose babyðŸŒ»,Ya Allah jaringan @byu_id jelek bgt udah hubun...,Ya Allah jaringan jelek bgt udah hubungin CS d...,ya allah jaringan jelek bgt udah hubungin cs d...,"['ya', 'allah', 'jaringan', 'jelek', 'bgt', 'u...","['allah', 'jaringan', 'jelek', 'bgt', 'udah', ...",allah jaringan jelek banget sudah hubungin cs ...,1.0
4,4,4,4,2021-06-30 22:05:43,1410358915850588179,Fructose babyðŸŒ»,@amourtabells @byu_id Paket unlimited Xl 1 bul...,Paket unlimited Xl bulan kaya byu mbps yang be...,paket unlimited xl bulan kaya byu mbps yang be...,"['paket', 'unlimited', 'xl', 'bulan', 'kaya', ...","['paket', 'unlimited', 'xl', 'kaya', 'byu', 'm...",paket unlimited xl kaya byu mbps bebas pakai p...,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1388,1724,1805,1805,2021-06-22 15:18:45,1407357398679900169,Mengandung amarah tidak bisa dilahirkan,"Ingin jdi gamer noob? Ayo, pakai @byu_id hanya...",Ingin jdi gamer noob Ayo pakai hanya dengan ri...,ingin jdi gamer noob ayo pakai hanya dengan ri...,"['ingin', 'jdi', 'gamer', 'noob', 'ayo', 'paka...","['jdi', 'gamer', 'noob', 'ayo', 'pakai', 'ribu...",jadi gamer noob ayo pakai ribu perbulan kecepa...,1.0
1389,1725,1806,1806,2021-06-22 15:06:49,1407354394551615488,Safira Dhyanti,Nanya sama mimin @byu_id gapernah di bales :(,Nanya sama mimin gapernah di bales,nanya sama mimin gapernah di bales,"['nanya', 'sama', 'mimin', 'gapernah', 'di', '...","['nanya', 'mimin', 'gapernah', 'bales']",nanya admin gapernah bales,0.0
1390,1726,1807,1807,2021-06-22 15:06:49,1407354392165044225,Stand Up Comedy Pekanbaru,"@byu_id lagi ada acara keren banget ini, Impro...",lagi ada acara keren banget ini Improv Comedy ...,lagi ada acara keren banget ini improv comedy ...,"['lagi', 'ada', 'acara', 'keren', 'banget', 'i...","['acara', 'keren', 'banget', 'improv', 'comedy...",acara keren banget improv comedy show sudah ba...,1.0
1391,1727,1808,1808,2021-06-22 15:04:47,1407353883156877312,feb,knp si gangguan mulu\n\np\n@byu_id,knp si gangguan mulu,knp si gangguan mulu,"['knp', 'si', 'gangguan', 'mulu']","['knp', 'gangguan', 'mulu']",kenapa gangguan mulu,0.0
1392,1728,1809,1809,2021-06-22 12:37:45,1407316880168161281,METE METE,Yang butuh hiburan secara gratis tis tis\nNont...,Yang butuh hiburan secara gratis tis tis Nonto...,yang butuh hiburan secara gratis tis tis nonto...,"['yang', 'butuh', 'hiburan', 'secara', 'gratis...","['butuh', 'hiburan', 'gratis', 'tis', 'tis', '...",butuh hiburan gratis tis tis nonton via zoom s...,1.0

In [53]:
df.to_csv('data fix\datalabeled.csv')
df.to_excel('data fix\datalabeled.xlsx')